const List<String> monstrosFoco = [
  'Aptonoth',
  'Anjanath',
  'Barroth',
  'Diablos',
  'Pukei-Pukei',
  'Apceros',
  'Kelbi',
  'Mosswine',
  'Hornetaur',
  'Dodogama',
  'Azure Rathalos',
  'Bezelgeuse',
  'Black Diablos',
  'Nergigante',
  'Teostra',
  'Deviljho',
  'Pink Rathian',
  'Lunastra',
];